# Generated by Django 4.1.7 on 2023-07-13 08:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allcourse',
            fields=[
                ('courseName', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('coursefee', models.IntegerField()),
                ('courseduration', models.IntegerField()),
                ('syllabus', ckeditor.fields.RichTextField(default='syllabus')),
                ('aboutsyllabus', ckeditor.fields.RichTextField(default='aboutsyllabus')),
                ('stars', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('Phone_number', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_designation', models.CharField(max_length=100)),
                ('trainer_experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.allcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('candidateId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=20)),
                ('Phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(max_length=150)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(default='Basic', max_length=100)),
                ('computer_knowledge', models.CharField(default='Basic', max_length=100)),
                ('course', models.CharField(max_length=80)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.trainer')),
            ],
        ),
    ]
