# Generated by Django 4.1.7 on 2023-07-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='computer_knowledge',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPaid', models.IntegerField()),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='unpaid', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.register')),
            ],
        ),
    ]
