# Generated by Django 4.1.7 on 2023-07-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodelform',
            name='username',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
