# Generated by Django 4.1.7 on 2023-07-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contactmodelform_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodelform',
            name='Phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
