# Generated by Django 4.1.7 on 2023-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contactmodelform_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('date', models.CharField(max_length=50)),
                ('logintime', models.CharField(max_length=50)),
                ('logouttime', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
