# Generated by Django 4.1.7 on 2023-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
